# version: '3.8'

# services:
#   neo4j:
#     image: neo4j:4.4.12-enterprise
#     container_name: neo4j-db
#     ports:
#       - "7474:7474"   # Browser
#       - "7687:7687"   # Bolt protocol
#     volumes:
#       - ./neo4j/data:/data
#       - ./import:/var/lib/neo4j/import
#     environment:
#       NEO4J_AUTH: neo4j/test123
#       NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
#       NEO4JLABS_PLUGINS: '["apoc","graph-data-science"]'   # Added GDS here
#       NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
#       NEO4J_dbms_security_procedures_allowlist: "apoc.*,gds.*"
#       NEO4J_apoc_export_file_enabled: "true"
#       NEO4J_apoc_import_file_enabled: "true"
#     restart: unless-stopped

version: '3.8'

services:
  neo4j:
    image: neo4j:4.4.14-enterprise
    container_name: neo4j-db
    ports:
      - "7474:7474"   # Browser
      - "7687:7687"   # Bolt protocol
    volumes:
      - ./neo4j/data:/data
      - ./import:/var/lib/neo4j/import
    environment:
      NEO4J_AUTH: neo4j/test123
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4JLABS_PLUGINS: '["apoc","graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.*,gds.*"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
    restart: unless-stopped